services:
  laravel-php-apache-environment:
    build: .
    image: custom-laravel-php
    volumes:
      - ./doc-root:/var/www/html/
    ports:
      - 8090:80
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'test'              
      MYSQL_USER: 'sample'                
      MYSQL_PASSWORD: 'password'         
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
    - 3307:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1